branch-defaults:
  default:
    environment: wninit
  master:
    environment: wninit
global:
  application_name: wninit
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
