branch-defaults:
  default:
    environment: LowCost-env
  master:
    environment: LowCost-env
    group_suffix: null
global:
  application_name: wninit
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  repository: null
  sc: git
